// This file is autogenerated by CMake. Do not edit by hand.

#ifndef AGX_PYTHON_VERSION_H
  #define AGX_PYTHON_VERSION() "3.10.6"
  #define AGX_PYTHON_LIBRARY() "/usr/lib/x86_64-linux-gnu/libpython3.10.so"
#endif
