AGX Dynamics: Name.h File Reference
Name.h File Reference
#include <agx/String.h>
#include <agx/AtomicValue.h>
#include <agx/HashFunction.h>
#include <string.h>
#include <iosfwd>
#include <agx/PushDisableWarnings.h>
#include <agx/PopDisableWarnings.h>
Classes
class agx::Name
Representation of a name string.
Namespaces
agx
The agx namespace contains the dynamics/math part of the AGX Dynamics API.
Functions
bool agx::operator!= (const agx::String &str, const agx::Name &name)
bool agx::operator!= (const char *str, const agx::Name &name)
bool agx::operator!= (const std::string &str, const agx::Name &name)
AGXCORE_EXPORT agx::String operator+ (const agx::String &str, const agx::Name &name)
AGXCORE_EXPORT agx::String operator+ (const char *str, const agx::Name &name)
AGXCORE_EXPORT agx::String operator+ (const std::string &str, const agx::Name &name)
AGXCORE_EXPORT std::ostream & agx::operator<< (std::ostream &stream, const Name &name)
bool agx::operator== (const agx::String &str, const agx::Name &name)
bool agx::operator== (const char *str, const agx::Name &name)
bool agx::operator== (const std::string &str, const agx::Name &name)
void std::swap (agx::Name &lhs, agx::Name &rhs)
Function Documentation
operator+() [1/3]
AGXCORE_EXPORT agx::String operator+ (const agx::String & str, const agx::Name & name)
operator+() [2/3]
AGXCORE_EXPORT agx::String operator+ (const char * str, const agx::Name & name)
operator+() [3/3]
AGXCORE_EXPORT agx::String operator+ (const std::string & str, const agx::Name & name)
swap()
void std::swap (agx::Name & lhs, agx::Name & rhs)
Definition at line 323 of file Name.h.
References std::swap(), and agx::Name::swap().
Referenced by std::swap().